
###

GET http://localhost:3000/customers/customer:ca77b571-9642-45ec-bf72-8192901bd458
Content-Type: application/json; charset=utf-8
Authorization: Bearer 53535353

### 

POST http://localhost:3000/customers
Content-Type: application/json; charset=utf-8
Authorization: Bearer 53535353

{
    "name": "John1",
    "document": 1234567
}

###

PUT http://localhost:3000/customers/customer:12330911-712f-430d-aaff-162d2f04b0b5
Content-Type: application/json; charset=utf-8
Authorization: Bearer 53535353

{
    "name": "Renato2",
    "document": 234512
}



